basePath: /mementor
definitions:
  BasicResponse:
    properties:
      message:
        type: string
    type: object
  Education:
    properties:
      department:
        type: string
      place:
        type: string
    required:
    - department
    - place
    type: object
  GetMentorResponse:
    properties:
      _id:
        type: string
      canHelpWith:
        items:
          type: string
        type: array
      classesDone:
        type: integer
      description:
        type: string
      education:
        items:
          $ref: '#/definitions/Education'
        type: array
      email:
        type: string
      experienceSince:
        type: integer
      grade:
        enum:
        - junior
        - middle
        - senior
        type: string
      image:
        $ref: '#/definitions/Image'
      language:
        items:
          type: string
        type: array
      name:
        type: string
      programmingLanguage:
        items:
          type: string
        type: array
      surname:
        type: string
      tariff:
        items:
          $ref: '#/definitions/Tariff'
        type: array
      technology:
        items:
          type: string
        type: array
      validProfile:
        type: boolean
    required:
    - email
    - experienceSince
    - grade
    - name
    - programmingLanguage
    - surname
    - tariff
    - technology
    type: object
  Image:
    properties:
      144x144:
        type: string
      512x512:
        type: string
    type: object
  Mentor:
    properties:
      _id:
        type: string
      grade:
        enum:
        - junior
        - middle
        - senior
        type: string
      image:
        $ref: '#/definitions/Image'
      language:
        items:
          type: string
        type: array
      name:
        type: string
      programmingLanguage:
        items:
          type: string
        type: array
      surname:
        type: string
      tariff:
        items:
          $ref: '#/definitions/Tariff'
        type: array
    required:
    - grade
    - name
    - programmingLanguage
    - surname
    - tariff
    type: object
  PostAuthRequest:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  PostAuthResponse:
    properties:
      token:
        example: Bearer token
        type: string
    type: object
  PostBookingRequest:
    properties:
      customerName:
        type: string
      customerTelegram:
        type: string
      mentorId:
        type: string
      tariffIndex:
        maximum: 2
        minimum: 0
        type: integer
    required:
    - customerName
    - customerTelegram
    - mentorId
    type: object
  PostImageRequest:
    properties:
      base64:
        type: string
    type: object
  PostMentorRequest:
    properties:
      experienceSince:
        type: integer
      grade:
        items:
          type: string
        type: array
      maxPrice:
        type: integer
      minPrice:
        type: integer
      search:
        type: string
    type: object
  PostMentorResponse:
    properties:
      mentors:
        items:
          $ref: '#/definitions/Mentor'
        type: array
      pages:
        type: integer
    required:
    - mentors
    - pages
    type: object
  PutMentorRequest:
    properties:
      _id:
        type: string
      canHelpWith:
        items:
          type: string
        type: array
      classesDone:
        type: integer
      description:
        type: string
      education:
        items:
          $ref: '#/definitions/Education'
        type: array
      email:
        type: string
      experienceSince:
        type: integer
      grade:
        enum:
        - junior
        - middle
        - senior
        type: string
      image:
        $ref: '#/definitions/Image'
      language:
        items:
          type: string
        type: array
      name:
        type: string
      programmingLanguage:
        items:
          type: string
        type: array
      surname:
        type: string
      tariff:
        items:
          $ref: '#/definitions/Tariff'
        type: array
      technology:
        items:
          type: string
        type: array
      validProfile:
        type: boolean
    required:
    - email
    - experienceSince
    - grade
    - name
    - programmingLanguage
    - surname
    - tariff
    - technology
    type: object
  Tariff:
    properties:
      description:
        maxLength: 255
        type: string
      name:
        type: string
      price:
        type: integer
    required:
    - description
    - name
    - price
    type: object
host: api.ilyaprojects.com
info:
  contact:
    email: mrmarkeld@gmail.com
    name: '@withoutasecondthought'
  description: Best backend ever.
  title: Mementor back
  version: "1.0"
paths:
  /book:
    post:
      consumes:
      - application/json
      description: book mentor of your dream
      parameters:
      - description: params
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/PostBookingRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/BasicResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BasicResponse'
      summary: New Booking
      tags:
      - booking
  /mentor:
    delete:
      description: remove mentor from bd
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/BasicResponse'
        "500":
          description: error occurred
          schema:
            $ref: '#/definitions/BasicResponse'
      summary: Delete mentor
      tags:
      - mentor
    get:
      description: get your page
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GetMentorResponse'
        "500":
          description: error occurred
          schema:
            $ref: '#/definitions/BasicResponse'
      summary: Show your Page
      tags:
      - mentor
    put:
      consumes:
      - application/json
      description: Send full mentor info to update your profile
      parameters:
      - description: Account info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/PutMentorRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/BasicResponse'
        "400":
          description: error occurred
          schema:
            $ref: '#/definitions/BasicResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/BasicResponse'
        "500":
          description: error occurred
          schema:
            $ref: '#/definitions/BasicResponse'
      summary: change mentor
      tags:
      - mentor
  /mentor/{id}:
    get:
      description: Give you mentor without personal fields
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GetMentorResponse'
        "404":
          description: error occured
          schema:
            $ref: '#/definitions/BasicResponse'
      summary: Show a mentor
      tags:
      - mentor
  /mentor/{page}:
    post:
      consumes:
      - application/json
      description: get mentors
      parameters:
      - description: number of page
        in: path
        name: page
        required: true
        type: integer
      - description: params
        in: body
        name: params
        schema:
          $ref: '#/definitions/PostMentorRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/PostMentorResponse'
        "400":
          description: error occurred
          schema:
            $ref: '#/definitions/BasicResponse'
        "500":
          description: error occurred
          schema:
            $ref: '#/definitions/BasicResponse'
      summary: return List of Mentors
      tags:
      - mentor
  /mentor/image:
    post:
      consumes:
      - application/json
      description: Upload your best photo
      parameters:
      - description: base64
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/PostImageRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/Image'
        "400":
          description: error occurred
          schema:
            $ref: '#/definitions/BasicResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/BasicResponse'
        "500":
          description: error occurred
          schema:
            $ref: '#/definitions/BasicResponse'
      summary: Upload Image
      tags:
      - mentor
  /sign-in:
    post:
      consumes:
      - application/json
      description: sign in
      operationId: sign-in
      parameters:
      - description: Account data
        in: body
        name: userinfo
        required: true
        schema:
          $ref: '#/definitions/PostAuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/PostAuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BasicResponse'
      summary: sign in
      tags:
      - auth
  /sign-up:
    post:
      consumes:
      - application/json
      description: sign up
      operationId: sign-up
      parameters:
      - description: Account data
        in: body
        name: userinfo
        required: true
        schema:
          $ref: '#/definitions/PostAuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/PostAuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BasicResponse'
      summary: sign up
      tags:
      - auth
securityDefinitions:
  ApiKeyAUth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
